#!/usr/bin/env bash
# Regenerate docs/INDEX.md from the YAML front matter of every page under docs/.
# Usage: scripts/build-docs-index.sh
set -euo pipefail

SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DOCS_DIR="$SKILL_DIR/docs"
OUT="$DOCS_DIR/INDEX.md"

[ -d "$DOCS_DIR" ] || { echo "no docs/ directory at $DOCS_DIR" >&2; exit 1; }

# Emit "<relative path>\t<title>" for every page, title taken from front matter.
list_pages() {
  find "$DOCS_DIR" -name '*.md' ! -name 'INDEX.md' -print0 \
  | sort -z \
  | while IFS= read -r -d '' f; do
      title="$(awk '
        NR==1 && $0!="---" { exit }
        NR>1  && $0=="---" { exit }
        /^title:[[:space:]]*/ {
          sub(/^title:[[:space:]]*/, "")
          gsub(/^["'"'"']|["'"'"']$/, "")
          print; exit
        }' "$f")"
      [ -n "$title" ] || title="$(basename "${f%.md}" | tr '_-' '  ')"
      printf '%s\t%s\n' "${f#"$DOCS_DIR"/}" "$title"
    done
}

# Human-readable heading for each top-level section.
section_label() {
  case "$1" in
    .)                 echo "Overview" ;;
    sql)               echo "SQL — syntax, statements, functions, data types" ;;
    data)              echo "Data import & export — CSV, JSON, Parquet, multi-file, partitioning" ;;
    guides)            echo "Guides — task-oriented how-tos" ;;
    clients)           echo "Clients — CLI, Python, Java, Go, Rust, Node, C, ODBC, WASM" ;;
    core_extensions)   echo "Core extensions — httpfs, spatial, postgres, iceberg, mysql, and more" ;;
    extensions)        echo "Extensions — installing, distributing, community extensions" ;;
    configuration)     echo "Configuration — settings, secrets, pragmas" ;;
    operations_manual) echo "Operations manual — deployment, security, footprint, logging" ;;
    connect)           echo "Connect — opening, attaching and detaching databases" ;;
    internals)         echo "Internals — storage format, execution, vectorization" ;;
    dev)               echo "Development — building DuckDB, sqllogictest, profiling" ;;
    quack)             echo "Quack — the DuckDB extension template tutorial" ;;
    *)                 echo "$1" ;;
  esac
}

PAGES="$(list_pages)"

{
  cat <<'HEADER'
# DuckDB documentation index

Every page bundled under `docs/`, grouped by section, with its path relative to
this directory. Use this index to pick the one page that answers the question,
then read it. To search by keyword across all pages instead, see
`reference/searching-docs.md`.

Generated by `scripts/build-docs-index.sh` — do not edit by hand.
HEADER
  echo

  # Section order: overview first, then the sections an agent reaches for most.
  for section in . sql data guides core_extensions extensions configuration \
                 clients connect operations_manual internals dev quack; do
    if [ "$section" = "." ]; then
      rows="$(printf '%s\n' "$PAGES" | grep -v '/' || true)"
    else
      rows="$(printf '%s\n' "$PAGES" | grep "^$section/" || true)"
    fi
    [ -n "$rows" ] || continue

    echo "## $(section_label "$section")"
    echo

    # Pages that sit directly in the section directory, then one block per subdirectory.
    direct="$(printf '%s\n' "$rows" | awk -F'\t' -v s="$section" '
      { p = $1; if (s != ".") sub("^" s "/", "", p); if (p !~ /\//) print }')"
    if [ -n "$direct" ]; then
      printf '%s\n' "$direct" | while IFS=$'\t' read -r path title; do
        printf -- '- `%s` — %s\n' "$path" "$title"
      done
      echo
    fi

    subdirs="$(printf '%s\n' "$rows" | awk -F'\t' -v s="$section" '
      { p = $1; if (s != ".") sub("^" s "/", "", p); if (p ~ /\//) { sub(/\/.*$/, "", p); print p } }' | sort -u)"
    for sub in $subdirs; do
      echo "### $section/$sub"
      echo
      printf '%s\n' "$rows" | grep "^$section/$sub/" | while IFS=$'\t' read -r path title; do
        printf -- '- `%s` — %s\n' "$path" "$title"
      done
      echo
    done
  done

  cat <<'FOOTER'
## Machine-readable function catalog

- `functions.json` — every built-in function with its parameters, return type,
  description and examples. Query it directly:
  `duckdb -c "FROM read_json_auto('docs/functions.json') LIMIT 5"`
FOOTER
} > "$OUT"

echo "wrote $OUT ($(grep -c '^- `' "$OUT") entries, $(wc -c < "$OUT") bytes)"
